### ISSUE TITLE
Pot issue

### ISSUE THREAD

**Issue by ajs65** [enfieldcat/ESP32_miniThrottle#3]
When using a pot with version 0.5 speed jumps from 0 to 23%.  Then gets stuck at 23%. Ok with stable version using same pin and hardware setup.

**Comment by enfieldcat** [comment]
OK thanks for letting me know, I'll investigate.
It may be a few days before I resolved it.

**Comment by enfieldcat** [comment]
Can you try again?
I was able to replicate being stuck at 23%, found there was an issue using the wrong semaphore when accessing some variables.
In my initial testing this has come right.

**Comment by ajs65** [comment]
Will do, it may take me a few days. Thanks for looking at it

**Comment by ajs65** [comment]
Downloaded and compiled Dev Branch, Wi-Fi seems to have stopped working.  Rolled back to Stable all OK.
Detail:
Won't connect to AP
wifiscan shows no APs
wifimode set to both
Can connect to ESP32, but no IP address issued to client

**Comment by enfieldcat** [comment]
I've made some small adjustments to the command line interface of 0.5,
hopefully that will provide mode information now.

If you run "debug 2", then "wifi" and "nvs" commands with no parameters,
have you lost wifi settings? (this should work even with your existing
version.) Once this issue is resolved you can set "debug 1" (default) again.

If your mode is BOTH then you should have an access point running, is the
miniThrottle access point accessible? If the web interface is enabled can
you access the 192.168.4.1 page using a browser?

Note the storage layout on eeprom changes between versions 0.4 and 0.5.
Reverting to 0.4 you should still see any setting you had previously. Going
forward to 0.5 you are using a different eeprom segment, and your 0.4
settings are not accessible. I'd suggest you "export" (command) your
settings before changing versions, save a copy using notepad (or any other
editor), then replay them on the up-grade. Reset the upgrade and perhaps
after 30 seconds rerun "wifi" or "nvs" to check your settings.

**Comment by ajs65** [comment]
Ok all working now, have another issue.  Thanks for all your help.

**Comment by enfieldcat** [comment]
No further comments, so closing issue.
