### ISSUE TITLE
Crash after turnout operation 

### ISSUE THREAD

**Issue by ajs65** [enfieldcat/ESP32_miniThrottle#4]
Using DCC EX, system crashes after turnout has thrown/closed.  

Guru Meditation Error Core 1. Panic’ed (loadprohibited) exception was unhandled

**Comment by enfieldcat** [comment]
Ok, thank you for you feedback. I appreciate your persistence - I'd don't
get to test all permutations of the software and a simple fix/typo
somewhere may have unintended consequences elsewhere.

Can you tell me a bit more? Version 0.5? Connecting over wifi to DCC-Ex,
and using protocol of WiThrottle/JMRI or DCC-Ex? Running a protocol command
will show this.

As usual it may take a few days for me to replicate and resolve the issue.

**Comment by ajs65** [comment]
Latest from 2 days ago, Wi-Fi Direct connection to DCC EX. Protocol DCC Ex.  If you point me to the area of source code, that you think may be the culprit, happy to try and debug on my test setup.

**Comment by enfieldcat** [comment]
I'd suspect the issue to be in file dispatch command.ino in the setTurnout
routine. This should take parameters of index number to the internal
turnout table, and a desired state. Then since you are running DCC-Ex
protocol, look fo the CMD protocol == DCCEX line.

But perhaps before doing that set "debug 3" - this should give bit of a
track and trace as to what subroutines you go through. Not all will be
reported, but certainly to the level of set turnout they will. It may we'll
be somewhere else unexpected. You'll not have to recompile to get the
additional debug output.

I suspect it is likely to be something like a buffer overflow or using %s
when a %c is required in forming a command string.

**Comment by enfieldcat** [comment]
Also "dump turnout" will dump out your turnout structures, defined in
static_defs.h

**Comment by ajs65** [comment]
dispatchCommands.ino
if (routeList[n].state == '8' || routeList[n].state == '2')
Fails with no routes setup, added a route it then stopped crashing at the above line.

Need to exit turnout menu, back to menu;
Locomotives
Routes
Track Power
for turnouts to operate correctly changing from THROW to CLOSE, or CLOSE to THROW doesn't work without doing this.
If you stay in the turnouts list menu they will only move once to either THROW or CLOSE

**Comment by enfieldcat** [comment]
Ok thanks for that. It would have taken me some time to track that down
given it is caused by not having any routes defined. It might only be the
weekend before I get to implement a fix for it though.

**Comment by enfieldcat** [comment]
I think that is actually easily resolved, the loop was running against the
wrong count, sould be route count not turnoutCount. Updated git repo with
the following

void invalidateRoutes (int8_t turnoutNr, char state)
 {
 bool active;

 for (uint8_t n=0; n<routeCount; n++) {
   if (xSemaphoreTake(routeSem, pdMS_TO_TICKS(TIMEOUT)) == pdTRUE) {
     if (routeList[n].state == '8' || routeList[n].state == '2') active =
true;
     else active = false;

**Comment by ajs65** [comment]
I’ll check it out over the weekend.  Always happy to help debug.
